### ISSUE TITLE
Turbolinks issue

### ISSUE THREAD

**Issue by ssoulless** [luizpicolo/tawk-rails#1]
It's now working when Turbolinks is enabled.

**Comment by luizpicolo** [comment]
Yes, in all my tests it worked correctly

**Comment by ssoulless** [comment]
Are you sure it is working with Turbolinks enabled? Because mine is not.

**Comment by ssoulless** [comment]
I confirm this issue, after remove turbo links the script started working, I will make a PR soon that fixes this issue.

**Comment by ssoulless** [comment]
Fixed! I just made a PR #2

**Comment by luizpicolo** [comment]
Tanks :+1:
