### ISSUE TITLE
insert tawk js into body seems like buggy

### ISSUE THREAD

**Issue by enkhchuluun** [luizpicolo/tawk-rails#3]
It works on first few pages, but after that it stops working.

i've inserted following js right before </body> tag on each page.

<script type="text/javascript">
    console.log('tawk');
    //window.$_Tawk = undefined;
    delete(window.$_Tawk);
    delete(window.$_Tawk_API);
    delete(window.$_Tawk_LoadStart);
    var $_Tawk_API={},$_Tawk_LoadStart=new Date();
    (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/XXXXXX/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
    })();
</script>

**Comment by luizpicolo** [comment]
This bug has been fixed in version 0.0.2. PR #2

**Comment by simoniong** [comment]
It's seems not, after insert `window.$_Tawk = undefined`, it work in first few page visit in Turbolink 5, but after that, it doesn't work again!
